# Cloud Build configuration for SOM API
# Triggers on push to main branch, builds and deploys to Cloud Run
#
# Setup:
# 1. Enable Cloud Build API: gcloud services enable cloudbuild.googleapis.com
# 2. Enable Cloud Run API: gcloud services enable run.googleapis.com
# 3. Enable Artifact Registry: gcloud services enable artifactregistry.googleapis.com
# 4. Create Artifact Registry repo:
#    gcloud artifacts repositories create som-docker \
#      --repository-format=docker \
#      --location=${_REGION} \
#      --description="SOM Docker images"
# 5. Grant Cloud Build permission to deploy to Cloud Run:
#    gcloud projects add-iam-policy-binding ${PROJECT_ID} \
#      --member="serviceAccount:${PROJECT_NUMBER}@cloudbuild.gserviceaccount.com" \
#      --role="roles/run.admin"
# 6. Connect GitHub repo in Cloud Build console

substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: som-api
  _ARTIFACT_REPO: som-docker

steps:
  # Step 1: Build Docker image
  # Note: Dockerfile uses pubspec.production.yaml directly
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest'
      - '-f'
      - 'api/Dockerfile'
      - '.'
    dir: '.'

  # Step 2: Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'SUPABASE_URL=${_SUPABASE_URL},SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '--set-secrets'
      - 'SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,SUPABASE_JWT_SECRET=SUPABASE_JWT_SECRET:latest'

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REPO}/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build
timeout: '1200s'
