import '../../../shared/som.dart';

final branchTags = branches
    .asMap()
    .entries
    .map((item) => TagModel(id: item.key.toString(), title: item.value));

const branches = [
  "Akupunktur",
  "Allergiebehandlung",
  "Allgemeinmedizin",
  "Altenpflege",
  "Ambulante Pflegedienste",
  "Apotheken",
  "Arzneimittel",
  "Ärztebedarf",
  "Augenoptik",
  "Brillen",
  "Chiropraktik",
  "Chirotherapie",
  "Chirurgie",
  "Diabetes",
  "Diagnostische Radiologie",
  "Eheberatung",
  "Entspannungstraining",
  "Ergotherapie",
  "Ernährungsberatung",
  "Familientherapie",
  "Fitnesscenter",
  "Frauenheilkunde, Geburtshilfe und Hebamme",
  "Fußpflege",
  "Gefäßchirurgie",
  "Gesundheitsberatung",
  "Gesundheitszentren",
  "Gynäkologie",
  "Haarentfernung",
  "Haarteile und Perücken",
  "Hals-Nasen-Ohrenheilkunde",
  "Hämatologie und Internistische Onkologie",
  "Heilpraktiker, Heilpädagogik",
  "Hörgeräte",
  "Hypnose",
  "Innere Medizin",
  "Kinder- und Jugendmedizin",
  "Körperpflegemittel",
  "Krankenkassen",
  "Krankenpflege / Pflegedienste",
  "Labor",
  "Logopädie",
  "Massagen",
  "Mund Kiefer Gesichtschirurgie",
  "Nahrungsergänzungsmittel",
  "Naturheilkunde",
  "Orthopädietechnik",
  "Paartherapie",
  "Permanent-Make-up",
  "Physiotherapie",
  "Psychotherapie",
  "Rehabilitationseinrichtungen",
  "Schmerztherapie",
  "Schönheitsoperationen",
  "Sportmedizin",
  "Urologie",
  "Wellness",
  "Zahnärzte / Zahnkliniken",
  "Zahntechnische Geräte und Bedarf",
  "Abschleppdienste",
  "Autoanhänger",
  "Autofolierung",
  "Automobile",
  "Autoverwerter und Schrottplätze",
  "Ersatzteile",
  "Fahrräder und Zubehör",
  "Fahrradverleih",
  "Fahrzeugaufbereitung",
  "Fahrzeugbau",
  "Flugzeuge",
  "Gebrauchtwagen",
  "KFZ-Sachverständige",
  "Limousinenservice",
  "Motorradzubehör und Bekleidung",
  "Navigationssysteme",
  "Nutzfahrzeuge",
  "Oldtimer und Restaurierung",
  "Parkhäuser",
  "Reifen",
  "Schifffahrt",
  "Tankstellen",
  "Taxi / Mietwagen",
  "Tuning",
  "Werkstatt und Reparatur",
  "Wohnwagen",
  "Computerreparaturen",
  "Drucker",
  "E-Commerce",
  "Informationstechnik-Dienstleistungen",
  "Kommunikationstechnik",
  "Notebooks",
  "Software",
  "Telekommunikation",
  "Beratungsstellen",
  "Bestattungsinstitute",
  "Brandschutz",
  "Büroservice",
  "Call-Center",
  "Casting-Agenturen",
  "Consulting",
  "Denkmalpflege",
  "Detektive / Detekteien",
  "Digitale Bildbearbeitung",
  "Diskjockeys",
  "Druckereien",
  "Energieversorgung",
  "Entrümpelungen",
  "Entsorgungsdienste",
  "Fahrschulen",
  "Friseursalons",
  "Haushaltsservice",
  "Hausmeisterdienste",
  "Internetagenturen",
  "Kosmetikstudios",
  "Marketingservice",
  "Mediation",
  "Onlinedienste",
  "Paketdienste",
  "Partnervermittlung",
  "Personaldienstleistungen",
  "Piercing",
  "Reinigungsbetriebe",
  "Schädlingsbekämpfung",
  "Schimmelpilzbekämpfung",
  "Schneebeseitigung",
  "Schneidereien",
  "Sicherheitsdienste",
  "Sonnenstudios",
  "Tätowierungen",
  "Transporte",
  "Unterhaltungsunternehmen",
  "Veranstaltungsservice",
  "Videoproduktion",
  "Werbung",
  "Wettannahmen",
  "Banken",
  "Bausparkassen",
  "Börsen",
  "Finanzdienstleistungen",
  "Gutachter / Sachverständige",
  "Inkassounternehmen",
  "Investmentgesellschaften",
  "Kapitalanlagen",
  "Leasing",
  "Notare",
  "Rechtsanwälte",
  "Rentenberatung",
  "Steuerberatung",
  "Versicherungen",
  "Bars",
  "Begleitservice",
  "Cafés",
  "Catering",
  "Diskotheken",
  "Eiscafés",
  "Gaststätten und Restaurants",
  "Nachtclubs",
  "Partyservice",
  "Pizzaservice",
  "Schausteller / Schaustellerbetriebe",
  "Weingut",
  "An- und Verkauf",
  "Antiquitäten",
  "Baby's- und Kinderbedarf",
  "Befestigungstechnik",
  "Beleuchtung",
  "Boote und Bootszubehör",
  "Brennmaterial, Brennstoff",
  "Buchhandel",
  "Bürobedarf",
  "Campingbedarf",
  "CDs und Schallplatten",
  "Dekorationsartikel",
  "Diabetikerbedarf",
  "Düngemittel",
  "Edelmetalle",
  "Einbruchsicherungen",
  "Einkaufszentrum",
  "Einzelhandel",
  "Eisenwaren",
  "Elektrogeräte",
  "Erotikartikel",
  "Fabrikverkauf",
  "Fahnen",
  "Fitnessgeräte",
  "Fliesen",
  "Gärtnereien & Blumenläden",
  "Getränkehandel",
  "Glas- und Porzellanwaren",
  "Handarbeitsbedarf",
  "Handelsvertretungen",
  "Handys",
  "Haushaltswaren",
  "Hochzeitsausstattungen",
  "Import und Export",
  "Jalousien",
  "Juweliere",
  "Kassensysteme",
  "Kaufhäuser",
  "Kioskbetriebe",
  "Kleidung",
  "Koffer und Taschen",
  "Kosmetik",
  "Lebensmittel",
  "Lederwaren",
  "Malerbedarf",
  "Möbel",
  "Musikinstrumente und -zubehör",
  "Öfen und Herde",
  "Parfümeriewaren",
  "Pumpen",
  "Reinigungsbedarf",
  "Saunaanlagen und -zubehör",
  "Schilder",
  "Schließanlagen",
  "Schmuck",
  "Schuhe",
  "Spielzeug",
  "Tabak und Tabakwaren",
  "Technischer Bedarf",
  "Uhren und Uhrenzubehör",
  "Verbrauchermärkte",
  "Verpackungen und Verpackungsmittel",
  "Werkzeuge",
  "Zeitungen und Zeitschriften",
  "Zoohandlungen",
  "Bäckereien",
  "Brennerei",
  "Elektrotechnik",
  "Fliesenleger",
  "Fotografen & Fotostudios",
  "Holzbe- und -verarbeitung",
  "Imkereien",
  "Kältetechnik",
  "Kaminbau",
  "Klempner",
  "Lackierereien",
  "Malerbetriebe",
  "Metallbe - und -verarbeitung",
  "Orgelbau",
  "Polsterei",
  "Restaurierungen",
  "Schlossereien",
  "Schmieden",
  "Schornsteinfeger",
  "Schreinereien",
  "Schweißereien",
  "Zimmereien",
  "Architektur",
  "Außenanlagen",
  "Bauberatung",
  "Bauelemente",
  "Baumärkte",
  "Baumaschinen und -geräte",
  "Baustoffe",
  "Bauunternehmen",
  "Dach und Bedachungen",
  "Fassaden",
  "Fenster",
  "Garagen und Carports",
  "Garten- und Landschaftsbau",
  "Haustechnik",
  "Holzhäuser",
  "Immobilien",
  "Immobilienmakler",
  "Innenausbau",
  "Inneneinrichtung",
  "Klimaanlagen",
  "Naturstein",
  "Vermessungsbüros",
  "Abfallentsorgung",
  "Abwassertechnik",
  "Arbeitsschutzbekleidung",
  "Auftragsvermittlung",
  "Brennstoffe",
  "Businesscenter",
  "Chemikalien",
  "Container",
  "Datenkommunikation",
  "Datenverarbeitung",
  "Drehereien",
  "Druckerzeugnisse",
  "Drucklufttechnik",
  "Edelstahl und -verarbeitung",
  "Elektromaschinen und -motoren",
  "Energieberatung",
  "Fahrbahn- und Bodenmarkierungen",
  "Fördertechnik",
  "Gebäudetechnik",
  "Gießereien",
  "Hebebühnen",
  "Hebezeuge",
  "Hochbau",
  "Hydraulik",
  "Imbissbedarf und -einrichtungen",
  "Industrieanlagenbau",
  "Industriebedarf",
  "Ingenieurbüros",
  "Kühlanlagen",
  "Kunststoffverarbeitung",
  "Labortechnik",
  "Lasertechnik",
  "Lüftungskanäle und -rohre",
  "Markt- und Meinungsforschung",
  "Maschinenbau",
  "Messgeräte und -werkzeuge",
  "Metallbau",
  "Nachrichtentechnik",
  "Oberflächentechnik",
  "Projektmanagement",
  "Pulverbeschichtungen",
  "Recycling",
  "Rohrpostanlagen",
  "Sandstrahlarbeiten",
  "Schaltanlagen und -geräte",
  "Schmierstoffe",
  "Schrott",
  "Sicherheitstechnik",
  "Sondermaschinenbau",
  "Stahlbau",
  "Steuerungs- und Antriebstechnik",
  "Tampondruck",
  "Tankanlagen und Tanks",
  "Tiefbau",
  "Tore",
  "Transformatoren",
  "Trocknungsanlagen",
  "Ultraschallreinigungsgeräte",
  "Umweltmanagement",
  "Umweltschutztechnik",
  "Unternehmensberatung",
  "Verchromungen",
  "Verpackungsbetriebe",
  "Verpackungsmaschinen und -geräte",
  "Walzwerke",
  "Werbemittel",
  "Werbetechnik",
  "Werkzeugbau",
  "Werkzeugmaschinen",
  "Wiegetechnik",
  "Wirtschafts- und Berufsverbände",
  "Wirtschaftsmediation",
  "Zeichenbüros",
  "Zeitarbeit",
  "Zeiterfassungssysteme",
  "Zellstoff",
  "Zerspanungsarbeiten",
  "Zugangskontrollsysteme",
  "Bibliotheken",
  "Bildhauer",
  "Design",
  "Fotografie",
  "Galerien",
  "Glaskunst",
  "Kunstgewerbe",
  "Kunsthandlungen",
  "Künstler",
  "Künstleragenturen",
  "Künstlerbedarf",
  "Kunstmaler",
  "Kunstschmieden",
  "Kunststopfereien",
  "Möbeldesign",
  "Modedesign",
  "Museen",
  "Musiktheater",
  "Theater",
  "Tiffany-Glaskunst",
  "Zauberkünstler",
  "Zirkusunternehmen",
  "Adressenverlage",
  "Anzeigenmittlung",
  "Filmausstattung",
  "Filmtechnik",
  "Internetportale",
  "Journalisten",
  "Konferenztechnik",
  "Materialprüfung",
  "Mediaagenturen",
  "Mediengestaltung und -entwicklung",
  "Mikrofilmtechnik",
  "Multimedia",
  "Nachrichtenagenturen",
  "Tonstudios",
  "Verlage",
  "Videofilme",
  "Autozulassungsdienste",
  "Behindertenwerkstätten",
  "Behörden",
  "Berufsfachschulen",
  "Berufsgenossenschaften",
  "Bundeswehr",
  "Einwohnermeldeämter",
  "Feuerwehren",
  "Gerichte",
  "Gewerkschaften",
  "Jugendzentren",
  "Justizvollzugsanstalten",
  "Kammern und Innungen",
  "Kinder- und Jugendhilfe",
  "Kindergärten",
  "Kindertagesstätten",
  "Kirchen und religiöse Gemeinschaften",
  "Konsulate",
  "Kreisverwaltungen",
  "Lohnsteuerhilfe",
  "Müllabfuhr",
  "Polizei",
  "Prüfstellen",
  "Rettungsdienste",
  "Sondermüllentsorgung",
  "Soziale Dienste",
  "Stadtführungen",
  "Straßenreinigung",
  "Stromversorgung",
  "Verbraucherberatung",
  "Wetterdienste",
  "Wissenschaftliche Institute",
  "Zollbehörden",
  "Au Pair",
  "Betriebsausflüge",
  "Busreisen",
  "Campingplätze",
  "Fährschifffahrt",
  "Ferien auf dem Bauernhof",
  "Ferienpark",
  "Ferienwohnungen",
  "Gasthöfe",
  "Geschäftsreisen",
  "Hafenrundfahrten",
  "Hochseilgärten",
  "Hotels",
  "Jugendheime und -herbergen",
  "Kanuvermietung",
  "Kurreisen",
  "Last-Minute-Reisen",
  "Messen und Ausstellungen",
  "Musicals",
  "Omnibusreisen",
  "Pensionen",
  "Reisebüros",
  "Reiterreisen",
  "Rundflüge",
  "Tagungshotels",
  "Tauchreisen",
  "Zimmervermietungen",
  "Berufsbildung",
  "Coaching",
  "Computerunterricht",
  "Erste-Hilfe-Ausbildung",
  "Erziehungsberatung",
  "Fort- und Weiterbildung",
  "Gabelstaplerfahrerschulungen",
  "Hochschulen",
  "Jagdschulen",
  "Karriereberatung",
  "Kunstschulen",
  "Lehrmittel",
  "Model- und Catwalktraining",
  "Modeschulen",
  "Musikunterricht",
  "Nachhilfeunterricht",
  "Privatschulen",
  "Schauspielschulen",
  "Sprachunterricht",
  "Angeln",
  "Badminton",
  "Ballett",
  "Ballonfahrten",
  "Bauchtanz",
  "Billiard",
  "Bogensport",
  "Bowling",
  "Briefmarken",
  "Eissport",
  "Fallschirmsport",
  "Fische",
  "Fitness",
  "Fotografie",
  "Geigen",
  "Gesangsunterricht",
  "Gitarren",
  "Golfplätze",
  "Gymnastik",
  "Hallenspielplätze",
  "Inline-Skating",
  "Kampfsport",
  "Kartsport",
  "Kinos",
  "Klaviere",
  "Klettern",
  "Kutschenfahrten",
  "Minigolf",
  "Modellbau",
  "Münzen",
  "Reiten",
  "Saunabäder",
  "Schachartikel",
  "Schwimmbäder",
  "Schwimmunterricht",
  "Skischule",
  "Snowboards",
  "Spielbanken",
  "Spielhallen",
  "Sportbedarf",
  "Squashcenter",
  "Surfsportbedarf",
  "Tanzschule",
  "Tauchsport",
  "Tennis",
  "Tischtennis",
  "Töpferkurse / Töpferei",
  "Videotheken",
  "Waffen und Munition",
  "Wandern",
  "Futtermittel",
  "Hundefutter",
  "Hundepflege",
  "Hundeschulen",
  "Katzenpensionen",
  "Katzenzucht",
  "Tierärzte",
  "Tierbedarf",
  "Tierfotografie",
  "Tierpflege und -betreuung",
  "Tierpsychologie",
  "Tierschulen",
  "Tierzucht",
  "Abendmodenverleih",
  "Anhängervermietung",
  "Barkassenvermietung",
  "Bootsvermietung",
  "Gartengerätevermietung",
  "Gästeanagement",
  "Klaviervermietung",
  "Konferenzräume",
  "Konzertsäle",
  "Kostümverleih",
  "Kranvermietung",
  "Maschinenvermietung",
  "Musikanlagen und -vermietung",
  "Partyzelte",
  "Seminarräume",
  "Skiverleih",
  "Smokingverleih",
  "Toilettenwagenvermietung",
  "Veranstaltungstechnik",
  "Yacht-Charter"
];
