name: som
version: '1.0'
summary: Smart Offer Manager
description: Smart Offer Manager

confinement: strict
base: core18

parts:
  som:
    plugin: flutter
    flutter-target: lib/main.dart

apps:
  som:
    command: som
    extensions: [flutter-master]
