include: package:lints/recommended.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
    prefer_final_locals: false
    avoid_print: false
    constant_identifier_names: false
